#!/bin/zsh
echo -e "${fg[green]}$0${reset_color} --> git add $HOME/Workspace/hexo${reset_color}"
git add $HOME/Workspace/hexo
date +"%F %T" | xargs -t -d'\n' git commit -m
echo -e "${fg[green]}$0${reset_color} --> git push -u origin master${reset_color}"
git push -u origin master
